name       : purpose
version    : 5.76.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/purpose-5.76.0.tar.xz : fd0edb0e7ba8b5336436848fe2452ff98c1b5bf2c49ea7744a8c0038d4e8887d
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for providing abstractions to get the developer's purposes fulfilled.
description: |
    This framework offers the possibility to create integrate services and actions on any application without having to implement them specifically. Purpose will offer them mechanisms to list the different alternatives to execute given the requested action type and will facilitate components so that all the plugins can receive all the information they need.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kwindowsystem-devel
rundeps    :
    - accounts-qml-module
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
