name       : purpose
version    : 5.54.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/purpose-5.54.0.tar.xz : 1cf4f4aeede1846cd1ef5fc524548745c95c1b6b7d134c427ae5d3cdf1423f1f
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Framework for providing abstractions to get the developer's purposes fulfilled.
description: |
    This framework offers the possibility to create integrate services and actions on any application without having to implement them specifically. Purpose will offer them mechanisms to list the different alternatives to execute given the requested action type and will facilitate components so that all the plugins can receive all the information they need.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
rundeps    :
    - accounts-qml-module
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove twitter since it doesn't work
    rm $installdir/usr/share/locale/*/LC_MESSAGES/purpose_twitter.mo
    rm $installdir/usr/share/accounts/services/kde/twitter-microblog.service
