name       : purpose
version    : 5.93.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.93/purpose-5.93.0.tar.xz : dc0bc0c7c5d9b27e21856132ceeb3893555a36f3944ebc97da2eb76a74e92cc4
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for providing abstractions to get the developer's purposes fulfilled.
description: |
    This framework offers the possibility to create integrate services and actions on any application without having to implement them specifically. Purpose will offer them mechanisms to list the different alternatives to execute given the requested action type and will facilitate components so that all the plugins can receive all the information they need.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(accounts-qt5)
    - pkgconfig(signond)
    - kaccounts-integration-devel
    - kdeclarative-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
rundeps    :
    - accounts-qml-module
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
