name       : purpose
version    : 5.51.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/purpose-5.51.0.tar.xz : 88024bee19b206dd6a109f4819f8a9f581d7544a812c0ff5618cd1abbae4b55e
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Framework for providing abstractions to get the developer's purposes fulfilled.
description: |
    This framework offers the possibility to create integrate services and actions on any application without having to implement them specifically. Purpose will offer them mechanisms to list the different alternatives to execute given the requested action type and will facilitate components so that all the plugins can receive all the information they need.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
rundeps    :
    - accounts-qml-module
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
