name       : purpose
version    : 5.77.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/purpose-5.77.0.tar.xz : bc48dbaa200336dafb5519ff63adf01c6bd22737a8c8423103e9c2d305f0f674
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Framework for providing abstractions to get the developer's purposes fulfilled.
description: |
    This framework offers the possibility to create integrate services and actions on any application without having to implement them specifically. Purpose will offer them mechanisms to list the different alternatives to execute given the requested action type and will facilitate components so that all the plugins can receive all the information they need.
builddeps  :
    - pkgconfig(accounts-qt5)
    - pkgconfig(libaccounts-glib)
    - pkgconfig(Qt5Qml)
    - pkgconfig(signond)
    - extra-cmake-modules
    - kaccounts-integration-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
    - kirigami2-devel
    - knotifications-devel
    - kwindowsystem-devel
rundeps    :
    - accounts-qml-module
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
