name       : purpose
version    : 5.46.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/purpose-5.46.0.tar.xz : e1cd55712726f9997cf616a36ae880a8f518b405da3b05d3b463418208d73ad7
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Framework for providing abstractions to get the developer's purposes fulfilled.
description: |
    This framework offers the possibility to create integrate services and actions on any application without having to implement them specifically. Purpose will offer them mechanisms to list the different alternatives to execute given the requested action type and will facilitate components so that all the plugins can receive all the information they need.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
